### ISSUE TITLE
no file requirements.txt in repo

### ISSUE THREAD

**Issue by Tudyx** [takuzoo3868/penta#11]

**Comment by benzetaa** [comment]
just write this (it's in Pipfile) and save as requirements.txt
 
autopep8
flake8
flake8-docstrings
flake8-double-quotes
flake8-import-order
pep8-naming
pytest
pytest-cov 
aiohttp
beautifulsoup4
dnspython
ipwhois
lxml
netifaces
paramiko
pillow
pymetasploit3
python-dateutil
python-dotenv
python-nmap
python-whois
requests
requests-html
selenium
shodan
sqlalchemy
tabulate
tqdm
ujson
xmltodict
pyyaml

**Comment by ghost** [comment]
┌──(radu㉿kali)-[~/penta]
└─$ pipenv run start -v
ERROR:root:Unable to locate configuration file
Traceback (most recent call last):
  File "/home/radu/penta/penta/penta.py", line 14, in <module>
    import modules
  File "/home/radu/penta/penta/modules/__init__.py", line 5, in <module>
    from .scan_msf import *  # noqa: F401,F403
  File "/home/radu/penta/penta/modules/scan_msf.py", line 52, in <module>
    msgrpc_pass = config.settings["METASPLOIT"]["MSGRPC_PASS"]
TypeError: 'NoneType' object is not subscriptable

**Comment by JingShen074** [comment]
> ┌──(radu㉿kali)-[~/penta] └─$ pipenv run start -v ERROR:root:Unable to locate configuration file Traceback (most recent call last): File "/home/radu/penta/penta/penta.py", line 14, in import modules File "/home/radu/penta/penta/modules/**init**.py", line 5, in from .scan_msf import * # noqa: F401,F403 File "/home/radu/penta/penta/modules/scan_msf.py", line 52, in msgrpc_pass = config.settings["METASPLOIT"]["MSGRPC_PASS"] TypeError: 'NoneType' object is not subscriptable

i got same question,how can i fix it
